Changed org.jvnet.hudson.plugins:plugin for org.jenkins-ci.plugins:plugin
Even the last version of org.jvnet.hudson.plugins:plugin was causing a NoClassDefFoundError for  com/sun/mirror/apt/AnnotationProcessorFactory when compiling with JDK7. Changed to org.jenkins-ci.plugins:plugin (1.424).